### ISSUE TITLE
R5RS support

### ISSUE THREAD

**Issue by svenha** [ktakashi/scheme-concurrent#1]
Is there a (partial) port to R5RS Scheme? I am interested in Schemes with efficient compiled programs, like Bigloo.

**Comment by ktakashi** [comment]
For R5RS, it'd be much more difficult than supporting R6RS or later as it doesn't have any standard module/library feature. So, it'd be almost impossible to make portable code for R5RS implementations. I'm not familiar with Bigloo, but if it supports R7RS library syntax, I might be able to port it.

**Comment by svenha** [comment]
Thanks for your explanation. Unfortunately, there is no R7RS library support in Bigloo, yet. So, your project is another example showing the strengths of R7RS :-)

**Comment by svenha** [comment]
Your code has been ported to bigloo: https://github.com/donaldsonjw/bigloo-concurrent .
